# PostgreSQL. Versions 9.1 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 864114
  port: 5432
  

development:
  <<: *default
  database: foosball_development

test:
  <<: *default
  database: foosball_test

production:
  <<: *default
  database: foosball_production
  username: foosball
  password: <%= ENV['GSD_DATABASE_PASSWORD'] %>